server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2023?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      exclude: application.yml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nuyahy.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
