server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PROVIDER-PAYMENT   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2

          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - After=2023-09-07T18:05:44.973+08:00[Asia/Shanghai]
            - Cookie=username,Eric
            - Header=X-Request-Id, \d+
            - Method=Get


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


